language: python

branches:
  only:
    - development

addons:
  sonarcloud:
    organization: "laserromae"

script:
  - nosetests --with-coverage --cover-package=src/app --cover-branches --cover-xml -v
  - sonar-scanner