language: python
python:
  - "3.6"

branches:
  only:
    - development

addons:
  sonarcloud:
    organization: "laserromae"

script:
  - nosetests --verbosity=3 --with-coverage --cover-package=src/app --cover-branches --cover-xml -v
  - sonar-scanner